apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: jfall1-topic
  labels:
    strimzi.io/cluster: jfall-kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: jfall2-topic
  labels:
    strimzi.io/cluster: jfall-kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824